### ISSUE TITLE
Not properly working on recent version ‪0.4.315‬

### ISSUE THREAD

**Issue by Tumpo** [m4heshd/whatsapp-desktop-dark#114]
Not properly working on recent version ‪0.4.315‬.

**Comment by EggY0lk** [comment]
![image](https://user-images.githubusercontent.com/27946481/72663862-362e4800-3a32-11ea-83de-132d81ff95f5.png)
dark mode not working correctly
![image](https://user-images.githubusercontent.com/27946481/72663915-b48aea00-3a32-11ea-9373-f0074dc021a5.png)

**Comment by tomasmiksa** [comment]
I have the same problem. Is someone still working on this project, or is it another death one?

**Comment by daniel-san-fried** [comment]
Same Problem here.

**Comment by NicolasPL64** [comment]
Same shit here xDDDDDDDDDDDDDDD

**Comment by abicelis** [comment]
Can confirm the same on macOS

**Comment by Syskoh** [comment]
![HHVZtglVgU](https://user-images.githubusercontent.com/33936608/72680114-7505e180-3ab6-11ea-9d3b-261645971374.png)
![8mHksqE1bb](https://user-images.githubusercontent.com/33936608/72680117-7b945900-3ab6-11ea-8bb8-f97b604e6d19.png)

Not as bad as  SwaggyHerosity's but still not working properly

**Comment by pjetr3k** [comment]
same as issue #113 , broken after the update

**Comment by NCheok** [comment]
Definitely need an update on this project, reverting back to normal mode for now.

**Comment by uropek-cyber** [comment]
same here

**Comment by Ingenieurs** [comment]
same issue here
little Workaround:
uninstall Dakmode, uninstall Whatsapp, install WhatsApp, install Darkmode.
However, this works only up to the next reboot

**Comment by dutzi** [comment]
Found a workaround.

Turns out there's a [userstyle](https://userstyles.org/styles/142096/dark-whatsapp-theme-by-mew) that turns WhatsApp web to dark mode, so all you need to do is get [its CSS file](https://pastebin.com/raw/2n79wfsD), (which I placed in pastebin, otherwise you'll need to install [stylus](https://chrome.google.com/webstore/detail/stylus/clngdbkpkpeebahjckkjfobafhncgmne?hl=en) or similar and extract it yourself)  and copy it to `<REPO_ROOT>/styles/<OS>/dark.css`, overwriting the current CSS.

Then you need to rebuild the binaries. (`npm run dist-mac` or `npm run dist-win`).

Then re-install the theme.

If you installed from binaries, I'm pretty sure you can overwrite `<BINARY_ROOT>/styles/<OS>/dark.css` and run the binary.

I hope you appreciate this screenshot below because it took my a while to redact this super confidential conversation with a friend about CSS and stuff:

![image](https://user-images.githubusercontent.com/927310/72727636-1ca51180-3b94-11ea-87a8-b77ec5e95a36.png)

**Comment by iambudi** [comment]
What is it now?

<img width="441" alt="image" src="https://user-images.githubusercontent.com/31809529/72731321-1760ba80-3bc6-11ea-8b81-47e4eca11794.png">

**Comment by Tumpo** [comment]
I have problems with rebuilding. Getting errors about ResourceHacker.

**Comment by iambudi** [comment]
Follow @dutzi above to make it work without rebuilding, simply by replacing the css file with the on he shared on pastebin.

**Comment by abicelis** [comment]
Yeap, fix by @dutzi works on macOS version.

**Comment by Tumpo** [comment]
@iambudi @abicelis Are you on Mac OS? On Windows 10 I get bit better dark mode with @dutzi fix but it's still pretty much unusable for me.

Search bar, chat list + link preview backgrounds is bright light colored.

**Comment by abicelis** [comment]
@Tumpo Yes. Works perfect on macOS. Weird that it's different on Windows?

**Comment by Ingenieurs** [comment]
> 
> 
> Weird that it's different on Windows?

@abicelis The Search bar on the left side is white colored. The icons of microphones and the read checkmark are grey and unvisible if the message is not read.

In the chat box are the time indications of audios in black style and therefore illegible.
X Buttons of for example Contactinformation is also invisible because its too light grey.

**Comment by MarioFlying** [comment]
Hello, I'm sure that m4heshd will provide a fix soon enough but in the meanwhile I'm able to run the dark mode as intended simply executing `C:\Users\MY_USERNAME\AppData\Local\WhatsApp\app-0.3.9309\Whatsapp.exe` instead of `C:\Users\MY_USERNAME\AppData\Local\WhatsApp\Whatsapp.exe`.

It seems to work just fine and it can't update over itself, since the update is already installed in the `app-0.4.315` folder -- which I'm just leaving there.
I hope it works for you guys as well. Bye

**Comment by Ingenieurs** [comment]
> 
> 
> Hello, I'm sure that m4heshd will provide a fix soon enough but in the meanwhile I'm able to run the dark mode as intended simply executing `C:\Users\MY_USERNAME\AppData\Local\WhatsApp\app-0.3.9309\Whatsapp.exe` instead of `C:\Users\MY_USERNAME\AppData\Local\WhatsApp\Whatsapp.exe`.

Yes that works also! Thanks :)

**Comment by NCheok** [comment]
@dutzi Thank you for this, this is actually a great fix for OSX.

For folks who want a little bit more simplified understanding, open and download the pastebin and save it as "dark.css".

Then move the new "dark.css" into the same folder you have for WADark now, and re-run the exec.

Everything will work as intended.

**Comment by atorresg** [comment]
works great! So, the app version is just an Electron wrapper of the last web version? Sorry, new to this group...

**Comment by ghost** [comment]
> @iambudi @abicelis Are you on Mac OS? On Windows 10 I get bit better dark mode with @dutzi fix but it's still pretty much unusable for me.
> 
> Search bar, chat list + link preview backgrounds is bright light colored.

I'm having the same problem here.

**Comment by atorresg** [comment]
it worked for me at the second attempt replacing dark.css

**Comment by ghost** [comment]
@atorresg windows version?

**Comment by snorreflorre** [comment]
> What is it now?
> 
> <img alt="image" width="441" src="https://user-images.githubusercontent.com/31809529/72731321-1760ba80-3bc6-11ea-8b81-47e4eca11794.png">

@iambudi This content is injected by the [CSS code](https://pastebin.com/raw/2n79wfsD) you saved to `dark.css`. See line 158‒175 of the modified file.

```css
/** Theme note. */
.app ._1qNwV .tzihe::before {
  display: block;
  margin-bottom: -20px;
  line-height: 1.3;
  font-size: 20px;
  color: var(--accent);
  content: var(--message) var(--changes) !important;
}
/** Theme info. */
.app ._1qNwV .tzihe::after {
  display: block;
  margin-top: 10px;
  padding-top: 10px;
  font-size: 16px;
  content: var(--version) !important;
  border-top: 1px solid var(--darker);
}
```
The variables used in the `var()` functions are globally defined for `:root` in line 8‒27.

```css
:root {
  --dark: #272c35;
  --darker: #1f232a;
  --light: #d1d1d1;
  --lighter: #e9e9e9;
  --accent: #7289da;
  --icon: #e1e1e1;
  --shadow: rgba(0, 0, 0, 0.1);
  --mred: #a3525b;
  --mgreen: #70a352;
  --mblue: #527aa3;
  --hover-delay: 0.8s;
  --image: url(https://media.discordapp.net/attachments/310799529161129984/417408747812552715/zilesanamin.jpg);
  --emojiOpacity: 0.75;
  --ui-font: "font_name", "Segoe UI", "Helvetica Neue", "Helvetica",
    "Lucida Grande", "Arial", "Ubuntu", "Cantarell", "Fira Sans", sans-serif;
  --version: "WhatsApp by Mew v1.7.1";
  --message: "Updated on 16th of January. Ported some fixes to v1. Please switch to v2 because v1 is unsupported! Also, please report issues on GitHub because I can't log into USo forums. ";
  --changes: "Visit https://github.com/vednoc/dark-whatsapp for more info.";
}
```

**Comment by atorresg** [comment]
> @atorresg windows version?

MacOS Mojave

**Comment by iambudi** [comment]
@snorreflorre Yes i realized this text, what i mean is about switching to v2.

**Comment by iambudi** [comment]
@Tumpo Yes, i'm using MacOS. There's still something needed to fix in one or two parts but overall it's usable. 
Surprisingly when i resize the window to a smaller one it will show just the picture profile in the chat list. Nice.

**Comment by luimunduk** [comment]
Contant window for me isn't completely black but I can live with that :)

**Comment by shangxor** [comment]
@dutzi Your fix works great for MacOS Catalina, thanks ;)

**Comment by firefinchdev** [comment]
@dutzi 's solution is applied in #119 .
@m4heshd please merge it.

**Comment by KeronCyst** [comment]
Isn't this v2 thing for WhatsApp Web, not Desktop? Stylus is a browser extension, not a desktop program/script...

**Comment by alcidesbsilvaneto** [comment]
> Found a workaround.
> 
> Turns out there's a [userstyle](https://userstyles.org/styles/142096/dark-whatsapp-theme-by-mew) that turns WhatsApp web to dark mode, so all you need to do is get [its CSS file](https://pastebin.com/raw/2n79wfsD), (which I placed in pastebin, otherwise you'll need to install [stylus](https://chrome.google.com/webstore/detail/stylus/clngdbkpkpeebahjckkjfobafhncgmne?hl=en) or similar and extract it yourself) and copy it to `<REPO_ROOT>/styles/<OS>/dark.css`, overwriting the current CSS.
> 
> Then you need to rebuild the binaries. (`npm run dist-mac` or `npm run dist-win`).
> 
> Then re-install the theme.
> 
> If you installed from binaries, I'm pretty sure you can overwrite `<BINARY_ROOT>/styles/<OS>/dark.css` and run the binary.
> 
> I hope you appreciate this screenshot below because it took my a while to redact this super confidential conversation with a friend about CSS and stuff:
> 
> ![image](https://user-images.githubusercontent.com/927310/72727636-1ca51180-3b94-11ea-87a8-b77ec5e95a36.png)

It's working!
Even my "npm install" giving me an error, the applications builds with no errors and now the dark mode is fully working! Thanks.

**Comment by firefinchdev** [comment]
@alcidesbsilvaneto yes this is working.
@jorgebirck @m4heshd I have implemented this working solution in #119 . Please merge it.

**Comment by exadeci** [comment]
Thanks @dutzi you actually just need to replace the `dark.css` and then launch WADark and it does it.

**Comment by mcbrineellis** [comment]
The workaround to replace the dark.css worked great for me.  Thank you!

**Comment by exadeci** [comment]
So now I have WhatsApp `Version 0.4.315` and when applying the theme WhatsApp asks to update on starting and only restoring the original theme allows me to use it.

I've tried updating as WhatsApp suggests and trying again but it's still the same, maybe they've made a breaking change.

**Comment by iambudi** [comment]
Today it does not work at all. Whatsapp keep asking for download the new update.

<img width="394" alt="image" src="https://user-images.githubusercontent.com/31809529/73430042-9fd21e80-436f-11ea-9232-62aaa4e5e1f9.png">

**Comment by haveneersrobin** [comment]
@iambudi I have the same issue

**Comment by m4heshd** [comment]
Everyone, please refer https://github.com/m4heshd/whatsapp-desktop-dark/pull/85#issuecomment-580186382.

**Comment by m4heshd** [comment]
Closing this since the issue is a duplicate of #113 and has been fixed in the latest release.

**Comment by snorreflorre** [comment]
> @snorreflorre Yes i realized this text, what i mean is about switching to v2.

@iambudi v2 of @vednoc's dark-whatsapp was just released 2 days ago. :)

https://github.com/vednoc/dark-whatsapp/releases/tag/2.0.0

**Comment by m4heshd** [comment]
Please stop linking third party style sheets that breaks the functionality of WADark. Users with less experience on these stuff starts using these style sheets and starts creating useless issues here which has nothing to do with WADark. I've mentioned that a few times already.
